server:
  port: 8070

spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
          format_sql: true
          highlight_sql: true
          use_sql_comments: true
    hibernate:
      ddl-auto: update # db 데이터 누적
    show-sql: true #sql을 console에서 볼 수 있도록

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE # 트랜잭션이 시작하고 끝나는걸 로그로 볼 수 있음
