server:
  port: 8070

spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create #jpa한테 ddl을 자동으로 해라
      show-sql: true #sql을 consol에서 볼 수 있도록
